import DetailBoardsImg from "../../constants/image/app/DetailBoards"

export const DetailFollowers = [
    {
        img:DetailBoardsImg.tadashi,
        name:'Tadashi',
        posts:'10',
        comments:'4000',
        likes:'65349'
    },
    {
        img:DetailBoardsImg.tadashi,
        name:'Tadashi',
        posts:'10',
        comments:'4000',
        likes:'65349'
    },
    {
        img:DetailBoardsImg.tadashi,
        name:'Tadashi',
        posts:'10',
        comments:'4000',
        likes:'65349'
    },
    {
        img:DetailBoardsImg.tadashi,
        name:'Tadashi',
        posts:'10',
        comments:'4000',
        likes:'65349'
    },
    {
        img:DetailBoardsImg.tadashi,
        name:'Tadashi',
        posts:'10',
        comments:'4000',
        likes:'65349'
    },
    {
        img:DetailBoardsImg.tadashi,
        name:'Tadashi',
        posts:'10',
        comments:'4000',
        likes:'65349'
    },
    {
        img:DetailBoardsImg.tadashi,
        name:'Tadashi',
        posts:'10',
        comments:'4000',
        likes:'65349'
    },
    {
        img:DetailBoardsImg.tadashi,
        name:'Tadashi',
        posts:'10',
        comments:'4000',
        likes:'65349'
    },
    {
        img:DetailBoardsImg.tadashi,
        name:'Tadashi',
        posts:'10',
        comments:'4000',
        likes:'65349'
    },
    {
        img:DetailBoardsImg.tadashi,
        name:'Tadashi',
        posts:'10',
        comments:'4000',
        likes:'65349'
    },
    {
        img:DetailBoardsImg.tadashi,
        name:'Tadashi',
        posts:'10',
        comments:'4000',
        likes:'65349'
    },
    {
        img:DetailBoardsImg.tadashi,
        name:'Tadashi',
        posts:'10',
        comments:'4000',
        likes:'65349'
    },
    {
        img:DetailBoardsImg.tadashi,
        name:'Tadashi',
        posts:'10',
        comments:'4000',
        likes:'65349'
    },
    {
        img:DetailBoardsImg.tadashi,
        name:'Tadashi',
        posts:'10',
        comments:'4000',
        likes:'65349'
    }
]